version: '2.0'

volumes:
  registry-data:
  gitea-data:
  go-server-data:
  drone-data:
  influxdb-data:
  grafana-data:

networks:
  public:
    external: true

services:

  proxy:
    build: github.com/nicholasdille/docker-cicd-env#traefik:traefik
    image: traefik
    depends_on:
      - web
      - gitea
      - go-server
      - drone
      - influxdb
      - grafana
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    labels:
      traefik.docker.network: public
      traefik.enable: true
      traefik.frontend.rule: HostRegexp:traefik.{domain:[a-z]+}
      traefik.port: 8080
      traefik.protocol: http

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - "registry-data:/var/lib/registry"
    networks:
      - public
      - default
    labels:
      traefik.docker.network: public
      traefik.enable: true
      traefik.frontend.rule: HostRegexp:registry.{domain:[a-z]+}
      traefik.port: 80
      traefik.protocol: http

  web:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
      - registry
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    networks:
      - public
      - default
    labels:
      traefik.docker.network: public
      traefik.enable: true
      traefik.frontend.rule: HostRegexp:hub.{domain:[a-z]+}
      traefik.port: 80
      traefik.protocol: http

  gitea:
    image: gitea/gitea
    environment:
      SSH_PORT: 2222
    ports:
      - "2222:22"
    volumes:
      - "gitea-data:/data"
    networks:
      - public
      - default
    labels:
      traefik.docker.network: public
      traefik.enable: true
      traefik.frontend.rule: HostRegexp:git.{domain:[a-z]+}
      traefik.port: 80
      traefik.protocol: http

  drone:
    image: drone/drone:0.8
    depends_on:
      - gitea
    volumes:
      - drone-data:/var/lib/drone/
    environment:
      DRONE_OPEN: "true"
      DRONE_HOST: http://127.0.0.1
      DRONE_GITEA: "true"
      DRONE_GITEA_URL: http://gitea:3000
      DRONE_SECRET: mydronesecret
    networks:
      - public
      - default
    labels:
      traefik.docker.network: public
      traefik.enable: true
      traefik.frontend.rule: HostRegexp:ci.{domain:[a-z]+}
      traefik.port: 80
      traefik.protocol: http

  drone-agent:
    image: drone/agent:0.8
    command: agent
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_SERVER: drone:9000
      DRONE_SECRET: mydronesecret

  influxdb:
    image: influxdb:alpine
    environment:
      INFLUXDB_DB: demo
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_READ_USER: read
      INFLUXDB_READ_PASSWORD: read
      INFLUXDB_WRITE_USER: write
      INFLUXDB_WRITE_PASSWORD: write
    volumes:
      - "influxdb-data:/var/lib/influxdb"

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    volumes:
      - "grafana-data:/var/lib/grafana"
    networks:
      - public
      - default
    labels:
      traefik.docker.network: public
      traefik.enable: true
      traefik.frontend.rule: HostRegexp:ops.{domain:[a-z]+}
      traefik.port: 80
      traefik.protocol: http

  telegraf:
    build: github.com/nicholasdille/docker-cicd-env#traefik:telegraf
    image: telegraf
    depends_on:
      - influxdb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
