version: '2.0'
volumes:
        registry-data:
        gitea-data:
        go-server-data:
        drone-data:
        influxdb-data:
        grafana-data:
services:
        proxy:
                build:
                        context: ./proxy
                image: proxy
                depends_on:
                        - web
                        - gitea
                        - go-server
                        - drone
                        - influxdb
                        - grafana
                ports:
                        - 80:80
        registry:
                image: registry
                ports:
                        - 5000:5000
                volumes:
                        - "registry-data:/var/lib/registry"
        web:
                image: konradkleine/docker-registry-frontend:v2
                ports:
                        - 8080:80
                depends_on:
                        - registry
                environment:
                        ENV_DOCKER_REGISTRY_HOST: registry
                        ENV_DOCKER_REGISTRY_PORT: 5000
        gitea:
                image: gitea/gitea
                environment:
                        - SSH_PORT=2222
                ports:
                        - 3000:3000
                        - "2222:22"
                volumes:
                        - "gitea-data:/data"
        go-server:
                image: gocd/gocd-server:v18.8.0
                ports:
                        - 8153:8153
                        - 8154:8154
                volumes:
                        - "go-server-data:/godata"
                depends_on:
                        - gitea
        dind:
                build:
                        context: ./dind
                image: dind
                privileged: true
                depends_on:
                        - registry
        go-agent:
                build:
                        context: ./go-agent
                image: go-agent
                depends_on:
                        - go-server
                        - gitea
                        - registry
                        - dind
                environment:
                        GO_SERVER_URL: https://go-server:8154/go
                        DOCKER_HOST: tcp://dind:2375
        drone:
                image: drone/drone:0.8
                ports:
                        - 8000:8000
                depends_on:
                        - gitea
                volumes:
                        - drone-data:/var/lib/drone/
                environment:
                        - DRONE_OPEN=true
                        - DRONE_HOST=http://127.0.0.1
                        - DRONE_GITEA=true
                        - DRONE_GITEA_URL=http://gitea:3000
                        - DRONE_SECRET=mydronesecret
        drone-agent:
                image: drone/agent:0.8
                command: agent
                depends_on:
                        - drone
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                environment:
                        - DRONE_SERVER=drone:9000
                        - DRONE_SECRET=mydronesecret
        influxdb:
                image: influxdb:alpine
                ports:
                        - 8086:8086
                environment:
                        INFLUXDB_DB: demo
                        INFLUXDB_ADMIN_USER: admin
                        INFLUXDB_ADMIN_PASSWORD: admin
                        INFLUXDB_READ_USER: read
                        INFLUXDB_READ_PASSWORD: read
                        INFLUXDB_WRITE_USER: write
                        INFLUXDB_WRITE_PASSWORD: write
                volumes:
                        - "influxdb-data:/var/lib/influxdb"
        grafana:
                image: grafana/grafana
                ports:
                        - 3001:3000
                depends_on:
                        - influxdb
                volumes:
                        - "grafana-data:/var/lib/grafana"
        telegraf:
                build:
                        context: ./telegraf
                image: telegraf
                depends_on:
                        - influxdb
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock"