version: '2.0'
services:
        registry:
                image: registry
                ports:
                        - 5000:5000
        web:
                image: konradkleine/docker-registry-frontend:v2
                ports:
                        - 8080:80
                depends_on:
                        - registry
                environment:
                        ENV_DOCKER_REGISTRY_HOST: registry
                        ENV_DOCKER_REGISTRY_PORT: 5000
        git:
                image: gitea/gitea
                ports:
                        - 3000:3000
        go-server:
                image: gocd/gocd-server:v18.6.0
                ports:
                        - 8153:8153
                        - 8154:8154
        dind:
                build:
                        context: ./dind
                image: demo-dind
                privileged: true
        go-agent:
                build:
                        context: ./go-agent
                image: demo-go-agent
                depends_on:
                        - go-server
                        - registry
                        - dind
                environment:
                        GO_SERVER_URL: https://go-server:8154/go
        influxdb:
                image: influxdb:alpine
                ports:
                        - 8086:8086
                environment:
                        INFLUXDB_DB: demo
                        INFLUXDB_ADMIN_USER: admin
                        INFLUXDB_ADMIN_PASSWORD: admin
                        INFLUXDB_READ_USER: read
                        INFLUXDB_READ_PASSWORD: read
                        INFLUXDB_WRITE_USER: write
                        INFLUXDB_WRITE_PASSWORD: write
        grafana:
                image: grafana/grafana
                ports:
                        - 3001:3000
                depends_on:
                        - influxdb
        telegraf:
                build:
                        context: ./telegraf
                image: demo-telegraf
                depends_on:
                        - influxdb
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock"
